version: '3.4'

volumes:
  datafiles:

services:
  database:
    image: mysql:8.0.26
    ports:
      - "3306:3306"
    volumes:
      - datafiles:/usr/local/mysql
      - "./contoso_inc.sql:/docker-entrypoint-initdb.d/1.sql"
    restart: always
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: yes
      MYSQL_DATABASE: contoso_inc_db
  api:
    build:
      context: .
      dockerfile: Dockerfile

    depends_on:
      - database
    ports:
      - "5000:80"
    restart: always
    environment:
      - DBHOST=database
      - ASPNETCORE_ENVIRONMENT=Production